services:
  post-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.prod
    ports:
      - 50051:50051
      - 5001:5001
    depends_on:
      - post-service-postgres
    networks:
      - post-service-network
      - auth-service-network
  post-service-postgres:
    image: postgres:17
    env_file: .env.prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - post_service_postgres_data:/var/lib/postgresql/data
    networks:
      - post-service-network

volumes:
  post_service_postgres_data:

networks:
  post-service-network:
    driver: bridge
  auth-service-network:
    driver: bridge